"""P0-G: self-improve must apply backpressure on duplicate pending approvals.

Behavioral audit found 17 pending `promote_perf-optimizer` approval
records — all generated by the same self-improve handler proposing the
same promotion day after day while Hector did not respond. The handler
never inspects the existing backlog before creating a new request, so
the pending queue keeps growing while the agent's signal-to-noise
collapses.

Fix contract:
  - Before running `auto_research.run_loop(agent_name)`, count pending
    approvals whose ``action`` is ``promote_<agent_name>``.
  - If the count meets the configurable threshold, skip the run and emit
    ``self_improve_paused_backlog_too_high`` with the agent name and the
    current pending count.
  - When Hector approves/rejects one of the existing pendings, the count
    drops below threshold and the loop resumes naturally on next tick.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from claw_v2.approval import ApprovalManager
from claw_v2.self_improve_backpressure import (
    SELF_IMPROVE_MAX_PENDING_PER_ACTION,
    count_pending_promote_approvals,
    should_pause_self_improve,
)


class SelfImproveBackpressureTests(unittest.TestCase):
    def setUp(self) -> None:
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.approvals = ApprovalManager(Path(self._tmp.name), secret="secret-x")

    def _seed_pending(self, action: str, count: int) -> None:
        for _ in range(count):
            self.approvals.create(action=action, summary=f"propose {action}")

    def test_empty_store_returns_zero_counts(self) -> None:
        self.assertEqual(count_pending_promote_approvals(self.approvals), {})

    def test_promote_actions_are_grouped_by_kind(self) -> None:
        self._seed_pending("promote_perf-optimizer", 3)
        self._seed_pending("promote_self-improve", 1)
        self._seed_pending("browser_use_task", 2)  # non-promote, ignored
        counts = count_pending_promote_approvals(self.approvals)
        self.assertEqual(counts.get("promote_perf-optimizer"), 3)
        self.assertEqual(counts.get("promote_self-improve"), 1)
        self.assertNotIn("browser_use_task", counts)

    def test_self_improve_does_not_spam_duplicate_pending_approvals(self) -> None:
        # Saturate the backlog above the default threshold.
        self._seed_pending("promote_perf-optimizer", SELF_IMPROVE_MAX_PENDING_PER_ACTION + 2)
        paused, pending = should_pause_self_improve(self.approvals, "perf-optimizer")
        self.assertTrue(paused)
        self.assertGreaterEqual(pending, SELF_IMPROVE_MAX_PENDING_PER_ACTION)

    def test_self_improve_runs_when_backlog_below_threshold(self) -> None:
        self._seed_pending("promote_perf-optimizer", SELF_IMPROVE_MAX_PENDING_PER_ACTION - 1)
        paused, pending = should_pause_self_improve(self.approvals, "perf-optimizer")
        self.assertFalse(paused)
        self.assertEqual(pending, SELF_IMPROVE_MAX_PENDING_PER_ACTION - 1)

    def test_approved_pendings_do_not_count_against_backpressure(self) -> None:
        # Create three pendings, approve one, leaving two pending.
        first = self.approvals.create("promote_perf-optimizer", "p1")
        self.approvals.create("promote_perf-optimizer", "p2")
        self.approvals.create("promote_perf-optimizer", "p3")
        self.approvals.approve(first.approval_id, first.token)
        paused, pending = should_pause_self_improve(
            self.approvals,
            "perf-optimizer",
            threshold=3,
        )
        self.assertFalse(paused)
        self.assertEqual(pending, 2)

    def test_archived_pendings_are_ignored(self) -> None:
        rec = self.approvals.create("promote_perf-optimizer", "p-arch")
        self.approvals.archive(rec.approval_id, reason="manual_skip")
        self.assertEqual(count_pending_promote_approvals(self.approvals), {})


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
